[package]
name = "multi-gpu-shadows"
version = "0.1.0"
edition = "2021"

[dependencies]
oxidx = { git = "https://github.com/if0ne/oxidx" }
#oxidx = "0.3.2"
gltf = "1.4.1"
glam = "0.29.2"
rand = "0.8"
parking_lot = "0.12.3"
winit = "0.30.2"